# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo_waiver',
            field=models.NullBooleanField(default=True, verbose_name='Photo Waiver Permission'),
        ),
    ]
