# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180117_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='height',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weight',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male'), (3, 'Gender fluid'), (4, 'Non-binary / Third gender'), (5, 'Prefer to self-describe'), (6, 'Prefer not to say')], null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True),
        ),
    ]
