# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 18:43
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180117_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Food Allergy'), (2, 'Skin Allergy'), (3, 'Dust Allergy'), (4, 'Insect Sting Allergy'), (5, 'Pet Allergies'), (6, 'Eye Allergy'), (7, 'Drug Allergies'), (8, 'Allergic Rhinitis (hay fever)'), (9, 'Latex Allergy'), (10, 'Mold Allergy'), (11, 'Pollen Allergy'), (12, 'Sinus Infection'), (13, 'Other (please specify)')], max_length=75),
        ),
    ]
