# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 06:39
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180119_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='food_allergens',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Milk'), (2, 'Eggs'), (3, 'Peanuts'), (4, 'Soy'), (5, 'Wheat'), (6, 'Tree nuts'), (7, 'Fish'), (8, 'Shellfish'), (9, 'Other (please specify)')], max_length=75),
        ),
    ]
