# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_medicalrecord_food_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='non_rx_type',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Tylenol'), (2, 'Ibuprofen'), (3, 'Both Ibuprofen or Tylenol')], null=True),
        ),
    ]
