# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180121_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
