# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20180124_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='height',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
