# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20180130_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='no_tetanus_vaccine',
            field=models.BooleanField(default=False),
        ),
    ]
