# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_medicalrecord_no_tetanus_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='amount_unit',
            field=models.IntegerField(blank=True, choices=[(1, 'Tablet'), (2, 'Spray'), (3, 'Puff'), (4, 'Gummy'), (5, 'Tbsp.'), (6, 'tsp.'), (7, 'oz'), (8, 'as needed')], null=True),
        ),
    ]
