# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20180206_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='non_rx_type',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Tylenol'), (3, 'Ibuprofen'), (4, 'Both Ibuprofen or Tylenol')], null=True),
        ),
    ]
