# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20180215_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='in_possession',
            field=models.BooleanField(default=False, verbose_name='NCI has possession'),
        ),
    ]
