# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20180216_1403'),
        ('students', '0015_medication_in_possession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministeredMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('guid', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fieldtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.FieldTrip')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Medication')),
            ],
            options={
                'verbose_name': 'Administered Meds',
                'verbose_name_plural': 'Administered Meds',
            },
        ),
    ]
