# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_administeredmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='administeredmed',
            name='time_administered',
            field=models.CharField(blank=True, choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Bedtime'), (5, 'Other...')], max_length=25),
        ),
    ]
