# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_administeredmed_time_administered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='amount_unit',
            field=models.IntegerField(blank=True, choices=[(1, 'Tablet'), (9, 'Lozenge'), (10, 'Pastilles'), (2, 'Spray'), (3, 'Puff'), (4, 'Gummy'), (13, 'Drop'), (5, 'Tbsp.'), (6, 'tsp.'), (7, 'oz'), (12, 'milligrams mg'), (11, 'micrograms mcg (μg)'), (8, 'as needed')], null=True),
        ),
    ]
