# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20180221_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='non_rx_type',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Tylenol'), (3, 'Ibuprofen'), (4, 'Ibuprofen or Tylenol')], null=True),
        ),
    ]
