# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20180222_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='waiver_agreement',
            field=models.NullBooleanField(default=False, verbose_name='Waiver Agreement'),
        ),
    ]
