# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20180312_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='guardian_supplies_food',
            field=models.BooleanField(default=False),
        ),
    ]
