# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_medicalrecord_guardian_supplies_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='amount_human',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
