# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_medication_amount_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administeredmed',
            name='time_administered',
        ),
        migrations.AddField(
            model_name='administeredmed',
            name='administered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
