# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20180402_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administeredmed',
            old_name='fieldtrip',
            new_name='field_trip',
        ),
    ]
