# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20180402_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
