# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20190704_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medical_agreement',
            field=models.NullBooleanField(default=True, verbose_name='Medical Agreement'),
        ),
    ]
