# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-26 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20190725_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderaddresses',
            name='reminder',
        ),
        migrations.DeleteModel(
            name='ReminderAddresses',
        ),
    ]
