# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-31 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20190725_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remindertemplates',
            options={'verbose_name_plural': 'reminder templates'},
        ),
        migrations.AddField(
            model_name='reminder',
            name='send_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
