# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='School, Business or Full Name')),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=75)),
                ('bio', models.TextField(blank=True, verbose_name='Profile Bio')),
                ('profile_photo', models.ImageField(blank=True, upload_to='contact-photos', verbose_name='Profile Photo')),
                ('profile_icon', models.ImageField(blank=True, upload_to='contact-icons', verbose_name='Profile Icon')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Customer ID')),
                ('account_type', models.CharField(blank=True, choices=[('parent', 'Parent/Guardian'), ('teacher', 'Teacher'), ('school', 'School'), ('ee-staff', 'EE Staff')], max_length=25, null=True)),
                ('legacy_user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID (Legacy Portal)')),
                ('legacy_username', models.CharField(blank=True, max_length=75, verbose_name='Username (Legacy Portal)')),
                ('legacy_school_id', models.IntegerField(blank=True, null=True, verbose_name='School ID (Legacy Portal)')),
                ('legacy_contact', models.CharField(blank=True, max_length=75, verbose_name='Contact Name (Legacy Portal)')),
                ('guid', models.CharField(blank=True, max_length=140)),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'Account Profile',
                'verbose_name_plural': 'Account Profiles',
            },
        ),
        migrations.CreateModel(
            name='AccountProfileAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(verbose_name='Street Address')),
                ('is_billing', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=75, verbose_name='Name of Insurance Company')),
                ('policy_num', models.CharField(blank=True, max_length=25, verbose_name='Policy #')),
                ('group_num', models.CharField(blank=True, max_length=25, verbose_name='Group #')),
                ('holder_name', models.CharField(blank=True, max_length=75, verbose_name="Policy Holder's Name")),
                ('guid', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Name of School')),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('legacy_school_id', models.IntegerField(blank=True, null=True, verbose_name='School ID (Legacy Portal)')),
                ('legacy_contact', models.CharField(blank=True, max_length=75, verbose_name='Contact Name (Legacy Portal)')),
                ('guid', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(verbose_name='Street Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.School')),
            ],
            options={
                'verbose_name': 'School Address',
                'verbose_name_plural': 'School Addresses',
            },
        ),
    ]
