# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='dependents_list',
            field=models.ManyToManyField(blank=True, related_name='insurance_dependents_list', to='students.Student'),
        ),
        migrations.AddField(
            model_name='accountprofileaddress',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='assoc_location_list',
            field=models.ManyToManyField(blank=True, related_name='contact_assoc_location_list', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
