# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180105_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='assoc_school_list',
            field=models.ManyToManyField(blank=True, related_name='account_assoc_school_list', to='accounts.School'),
        ),
    ]
