# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountprofile_assoc_school_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
