# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180112_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email_whitelist',
            field=models.TextField(blank=True, verbose_name='Email Whitelist'),
        ),
    ]
