# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_school_email_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email_whitelist',
            field=models.TextField(blank=True, help_text='Comma-separated list of teacher email addresses pre-approved to access this school.', verbose_name='Email Whitelist'),
        ),
    ]
