# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180129_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.IntegerField(blank=True, choices=[(0, 'General Note')], default=1, null=True)),
                ('message', models.TextField(blank=True)),
                ('guid', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of note')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.School')),
            ],
            options={
                'verbose_name': 'School Note',
                'verbose_name_plural': 'School Notes',
            },
        ),
    ]
