# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_schoolnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='guid',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
