# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180130_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of note'),
        ),
        migrations.AlterField(
            model_name='schoolnote',
            name='note_type',
            field=models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Billing & Payments'), (2, 'Phone call')], default=0, null=True),
        ),
    ]
