# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180130_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('public', 'Public School'), ('montessori', 'Montessori School')], default='public', max_length=15),
        ),
    ]
