# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountprofile_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('parent', 'Parent/Guardian'), ('teacher', 'Teacher'), ('school', 'School'), ('ee-staff', 'EE Staff')], max_length=25, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='classroom',
            field=models.IntegerField(blank=True, choices=[(1, "Children's house"), (2, 'Lower Elementary'), (3, 'Upper Elementary'), (4, 'Adolescent')], null=True, verbose_name='Classroom'),
        ),
    ]
