# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180710_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='classroom',
            field=models.IntegerField(blank=True, choices=[(1, "Children's house"), (2, 'Lower Elementary'), (3, 'Upper Elementary'), (4, 'Adolescent')], help_text='If this user is a Teacher or affilated with one of their schools classrooms, which is it?', null=True, verbose_name='Classroom'),
        ),
    ]
