# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 21:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_schoolfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfile',
            name='file',
            field=models.FileField(upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
