# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190930_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfile',
            old_name='isPublic',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='schoolfile',
            name='file_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
