# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-02 16:49
from __future__ import unicode_literals

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191002_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfile',
            name='file',
            field=models.FileField(upload_to=accounts.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
