# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('schema', jsonfield.fields.JSONField(blank=True)),
                ('uischema', jsonfield.fields.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', jsonfield.fields.JSONField(blank=True)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('reg_start_date', models.DateTimeField(blank=True, null=True)),
                ('reg_end_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('guid', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('legacy_fieldtrip_id', models.IntegerField(blank=True, null=True)),
                ('legacy_school_id', models.IntegerField(blank=True, null=True)),
                ('legacy_class_id', models.IntegerField(blank=True, null=True)),
                ('legacy_teacher_id', models.IntegerField(blank=True, null=True)),
                ('legacy_finalized', models.BooleanField(default=False)),
                ('building_list', models.ManyToManyField(blank=True, to='locations.Building')),
                ('customer_list', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('short_name', models.CharField(blank=True, max_length=140)),
                ('location_type', models.CharField(blank=True, choices=[('NONE', 'None'), ('EE', 'Environmental Education'), ('MS', 'Montessori School')], max_length=4, null=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('open_enrollment', models.BooleanField(default=False)),
                ('fact_sheet_file', models.FileField(blank=True, upload_to='locations/fact-sheets')),
                ('floor_plan_file', models.FileField(blank=True, upload_to='locations/floor-plans')),
                ('food_menu_file', models.FileField(blank=True, upload_to='locations/food-menus')),
                ('open_graph_image', models.FileField(blank=True, upload_to='locations/open-graph-images')),
                ('open_graph_desc', models.TextField(blank=True)),
                ('hero_image', models.FileField(blank=True, upload_to='locations/hero-images')),
                ('bg_image', models.FileField(blank=True, upload_to='bg-images')),
                ('body', models.TextField(blank=True)),
                ('sidebar_json', jsonfield.fields.JSONField(blank=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='VisitSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time', models.IntegerField(blank=True, choices=[(1, 'Classroom Observation'), (2, 'During off hours')], null=True)),
                ('location', models.IntegerField(blank=True, choices=[(1, "Children's House (Ages 3-6)"), (2, 'Lower Elementary (Ages 6-9)'), (3, 'Upper Elementary (Ages 9-12)'), (4, 'Adolescent (Ages 12-15)'), (5, 'Angelus Oaks, California'), (6, 'Ben Lomond, California'), (7, 'Bruceville, Texas'), (8, 'Wimberley, Texas'), (9, 'Lake Geneva, Wisconsin')], null=True)),
                ('personal_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='student_list',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
