# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 06:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='schema',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='uischema',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='assignment',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='sidebar_json',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
