# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
