# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180126_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Only enabled Field Trips will be visible on the site and portal.'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='school_list',
            field=models.ManyToManyField(blank=True, help_text='Select the school(s) that will be attending this field trip.', to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='student_list',
            field=models.ManyToManyField(blank=True, help_text='When Parents register their children, those registrations will show up here. You normally do not have to touch this field but is provided so you can manually add/remove students.', to='students.Student'),
        ),
    ]
