# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_address_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location'),
        ),
    ]
