# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20180216_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtrip',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
    ]
