# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20180219_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitsubmission',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, "Children's House (Ages 3-6)"), (2, 'Lower Elementary (Ages 6-9)'), (3, 'Upper Elementary (Ages 9-12)'), (4, 'Adolescent (Ages 12-15)'), (5, 'Angelus Oaks, California'), (6, 'Ben Lomond, California'), (7, 'Bruceville, Texas'), (8, 'New Ulm, Texas'), (9, 'Lake Geneva, Wisconsin')], null=True),
        ),
    ]
