# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20180222_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrip',
            name='expected_head_count',
            field=models.IntegerField(default=0),
        ),
    ]
