# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180222_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtrip',
            options={'get_latest_by': 'start_date', 'ordering': ['start_date']},
        ),
    ]
